PROJECT_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
DACPU_CONFIG_FILE := $(firstword $(wildcard $(PROJECT_DIR)dacpu-project.yaml) $(wildcard $(PROJECT_DIR)dacpu-template.yaml))

ifeq ($(strip $(DACPU_CONFIG_FILE)),)
$(error Could not locate DACPU project configuration file. $(CURDIR))
endif

ISA_CONFIG := $(abspath $(PROJECT_DIR)$(shell yq -r '.toolchain.isa' "$(DACPU_CONFIG_FILE)"))

TARGET   := [[[ project_name ]]]

CC       := gcc
LD       := g++

ZMQ_PREFIX  ?= $(HOME)/.local
ZMQ_INC     := $(ZMQ_PREFIX)/include
ZMQ_LIB     := $(ZMQ_PREFIX)/lib

CFLAGS   := -Wall -Wextra -O2 -I$(ZMQ_INC)
LDFLAGS  := -L$(ZMQ_LIB) -Wl,-u,spawn_enclave
LDLIBS   := -ldaedalus -lzmq -lncurses -lpthread -lstdc++

SRC_DIR  := .
OBJ_DIR  := obj
BIN_DIR  := bin

FIRMWARE_OBJ := $(OBJ_DIR)/firmware_image_dump.o

FIRMWARE_DIR := ./enclave
FIRMWARE_DUMP := $(FIRMWARE_DIR)/obj/firmware.c
FIRMWARE_SOURCE := $(shell find $(FIRMWARE_DIR) \
  -type f \( -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.S' -o -name 'Makefile' \) \
  -print | sort)

COMPILER_DIR := $(abspath ./toolchain/compiler)
COMPILER_SOURCE := $(shell find $(COMPILER_SRC) -type f -print | sort)
COMPILER_TOOL := $(COMPILER_DIR)/dist/compile.pyz

SRCS := $(wildcard $(SRC_DIR)/*.c)
OBJS := $(patsubst $(SRC_DIR)/%.c,$(OBJ_DIR)/%.o,$(SRCS)) $(FIRMWARE_OBJ)

PLATFORM_DIR := ./toolchain/platform
STATIC_LIBS := $(PLATFORM_DIR)/bin/server.a $(PLATFORM_DIR)/bin/platform.a $(PLATFORM_DIR)/bin/verilated_runtime.a

BOARD_SOURCE_FILES := $(shell find $(PLATFORM_DIR) \
  -type f \( -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.S' -o -name 'Makefile' \) \
  -print | sort)

all: $(BIN_DIR)/$(TARGET)

$(BIN_DIR)/$(TARGET): $(OBJS) $(STATIC_LIBS) | $(BIN_DIR)
	$(LD) $(OBJS) $(STATIC_LIBS) -o $@ $(LDFLAGS) $(LDLIBS)

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c | $(OBJ_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

$(COMPILER_TOOL): $(COMPILER_SOURCE)
	$(MAKE) -C $(COMPILER_DIR)

$(FIRMWARE_DUMP): $(FIRMWARE_SOURCE) $(COMPILER_TOOL)
	$(MAKE) -C $(FIRMWARE_DIR) COMPILER_TOOL=$(COMPILER_TOOL) ISA=$(ISA_CONFIG)

$(FIRMWARE_OBJ): $(FIRMWARE_DUMP) | $(OBJ_DIR)
	$(CC) $(CFLAGS) -c $(FIRMWARE_DUMP) -o $@

$(OBJ_DIR) $(BIN_DIR):
	mkdir -p $@

$(STATIC_LIBS): $(BOARD_SOURCE_FILES)
	$(MAKE) -C ./toolchain/platform

clean:
	rm -rf $(OBJ_DIR) $(BIN_DIR)
	$(MAKE) -C ./toolchain/platform clean
	$(MAKE) -C ./toolchain/compiler clean
	$(MAKE) -C $(FIRMWARE_DIR) clean

.PHONY: all clean
